### ISSUE TITLE
Account Management

### ISSUE THREAD

**Issue by VictorGreco** [namelessfy/namelessfy-app#9]
**User Story**
- [ ] User information display #27
- [ ] Edit user information #30
- [ ] Change user password #34
